version: "3.3"
services:
  db:
    image: postgres:11-alpine
    env_file:
      - .env_docker
    ports:
      - 5432:5432
    expose:
      - "5432"

  app:
    build: .
    restart: on-failure
    env_file:
      - .env_docker
    ports:
      - 8000:8000
    depends_on:
      - db